require('nvim.plugins.lualine')
require('nvim.plugins.telescope')
require('nvim.plugins.treesitter')
require('nvim.plugins.nvim-tree')
require('nvim.plugins.gitsigns')
require('nvim.plugins.copilot')
